In [ ]:
import pandas as pd
df = pd.read_excel("/content/CineMetrics_Dataset.xlsx")
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0

In [ ]:
df.describe()

,Movie_ID,Release_Year,Duration_Min,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
count,300.000000,300.000000,285.000000,264.000000,273.000000,282.000000,285.000000,279.000000,288.000000
mean,150.500000,2008.680000,112.564912,32.051515,83.763736,6.465957,89.589123,59.390681,19.805556
std,86.746758,8.854695,21.138048,34.471101,107.025831,1.339428,78.999020,15.403963,11.729695
min,1.000000,1995.000000,70.000000,2.100000,0.000000,3.200000,5.000000,25.000000,0.000000
25%,75.750000,2001.000000,98.000000,12.800000,22.600000,5.600000,26.500000,48.000000,10.750000
50%,150.500000,2009.000000,112.000000,22.100000,51.900000,6.450000,69.600000,59.000000,20.000000
75%,225.250000,2016.250000,127.000000,38.450000,109.900000,7.400000,128.200000,70.000000,30.000000
max,300.000000,2024.000000,166.000000,300.000000,906.000000,9.700000,413.800000,100.000000,40.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               285 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [ ]:
df["Duration_Min"] = df["Duration_Min"].fillna(df["Duration_Min"].mean())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [ ]:
df["Genre"] = df["Genre"].fillna(df["Genre"].mode()[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      300 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [ ]:
df.describe()

,Movie_ID,Release_Year,Duration_Min,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
count,300.000000,300.000000,300.000000,264.000000,273.000000,282.000000,285.000000,279.000000,288.000000
mean,150.500000,2008.680000,112.564912,32.051515,83.763736,6.465957,89.589123,59.390681,19.805556
std,86.746758,8.854695,20.601007,34.471101,107.025831,1.339428,78.999020,15.403963,11.729695
min,1.000000,1995.000000,70.000000,2.100000,0.000000,3.200000,5.000000,25.000000,0.000000
25%,75.750000,2001.000000,99.000000,12.800000,22.600000,5.600000,26.500000,48.000000,10.750000
50%,150.500000,2009.000000,112.564912,22.100000,51.900000,6.450000,69.600000,59.000000,20.000000
75%,225.250000,2016.250000,126.250000,38.450000,109.900000,7.400000,128.200000,70.000000,30.000000
max,300.000000,2024.000000,166.000000,300.000000,906.000000,9.700000,413.800000,100.000000,40.000000

In [ ]:
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,112.564912,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.000000,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.000000,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.000000,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.000000,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      300 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [ ]:
df["Budget_Million_USD"] = df["Budget_Million_USD"].fillna(df["Budget_Million_USD"].mode()[0])
df["Revenue_Million_USD"] = df["Revenue_Million_USD"].fillna(df["Revenue_Million_USD"].mode()[0])
df["IMDB_Rating"] = df["IMDB_Rating"].fillna(df["IMDB_Rating"].mode()[0])
df["Votes_Thousands"] = df["Votes_Thousands"].fillna(df["Votes_Thousands"].mode()[0])
df["Critic_Score"] = df["Critic_Score"].fillna(df["Critic_Score"].mode()[0])
df["Director_Experience_Years"] = df["Director_Experience_Years"].fillna(df["Director_Experience_Years"].mode()[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      300 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                300 non-null    float64
 11  Votes_Thousands            300 non-null    float64
 12  Critic_Score               300 non-null    float64
 13  Director_Experience_Years  300 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [ ]:
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,112.564912,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.000000,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,57.0,13.0
2,3,The Rising Illusion,Action,1995,105.000000,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.000000,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.000000,Hindi,India,Netflix,37.1,13.1,6.3,26.1,47.0,15.0